# Generated by Django 3.1.1 on 2020-11-13 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Best', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kospi50',
            name='id',
        ),
        migrations.AlterField(
            model_name='kospi50',
            name='code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='STOCKVALUES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('closeprice', models.IntegerField()),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Best.kospi50')),
            ],
        ),
        migrations.CreateModel(
            name='POSORNEG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('pos', models.IntegerField()),
                ('neg', models.IntegerField()),
                ('neu', models.IntegerField()),
                ('total', models.IntegerField()),
                ('pos_pn', models.IntegerField()),
                ('pos_pnn', models.IntegerField()),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Best.kospi50')),
            ],
        ),
        migrations.CreateModel(
            name='FINANCESTATE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_year', models.CharField(max_length=5)),
                ('date', models.DateField()),
                ('sales', models.IntegerField()),
                ('business_profit', models.IntegerField()),
                ('net_profit', models.IntegerField()),
                ('bp_percent', models.IntegerField()),
                ('np_percent', models.IntegerField()),
                ('roe', models.IntegerField()),
                ('debt_ratio', models.IntegerField()),
                ('quick_ratio', models.IntegerField()),
                ('reserve_ratio', models.IntegerField()),
                ('eps', models.IntegerField()),
                ('per', models.IntegerField()),
                ('bps', models.IntegerField()),
                ('pbr', models.IntegerField()),
                ('per_share', models.IntegerField()),
                ('dividend_rate', models.IntegerField()),
                ('propensity_rate', models.IntegerField()),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Best.kospi50')),
            ],
        ),
    ]
