# Generated by Django 3.1.1 on 2020-11-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Best', '0004_auto_20201120_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financestate',
            name='bp_percent',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='financestate',
            name='bps',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='financestate',
            name='business_profit',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='financestate',
            name='debt_ratio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='financestate',
            name='dividend_rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='financestate',
            name='eps',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='financestate',
            name='net_profit',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='financestate',
            name='np_percent',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='financestate',
            name='pbr',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='financestate',
            name='per',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='financestate',
            name='per_share',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='financestate',
            name='propensity_rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='financestate',
            name='quick_ratio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='financestate',
            name='reserve_ratio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='financestate',
            name='roe',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='financestate',
            name='sales',
            field=models.FloatField(),
        ),
    ]
