# Generated by Django 3.1.1 on 2020-11-25 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Best', '0005_auto_20201124_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorneg',
            name='neg_pn',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posorneg',
            name='neg_pnn',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='posorneg',
            name='pos_pn',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='posorneg',
            name='pos_pnn',
            field=models.FloatField(),
        ),
    ]
