# Generated by Django 3.1.1 on 2020-11-26 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Best', '0006_auto_20201125_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='POINTDATE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point1', models.DateField()),
                ('point2', models.DateField()),
                ('point3', models.DateField()),
                ('point4', models.DateField()),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Best.kospi50')),
            ],
        ),
    ]
